#
#
#
micronaut:
  application:
    name: pocMongodb
#
  params:
    mongodb:
      host    : ${MONGODB_HOST:xxx}
      username: ${MONGODB_USERNAME:xxx}
      password: ${MONGODB_PASSWORD:xxx}
      dbname  : ${MONGODB_DATABASE:learning_mongodb}
      collection : ${MONGODB_COLLECTION:tours}
#
mongodb:
  uri: "mongodb://${micronaut.params.mongodb.username}:${micronaut.params.mongodb.password}@${micronaut.params.mongodb.host}/${micronaut.params.mongodb.dbname}?retryWrites=true&w=majority&ssl=false&sslInvalidHostNameAllowed=true"
#   uri: "mongodb://localhost:27017"